language: scala

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt -J-Xmx4G clean test scripted

scala:
  - 2.10.6

jdk:
  - oraclejdk8

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9d59e247d947e8f6410
    on_success: change
    on_failure: always
    on_start: never
